# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Config
gems: [jekyll-gist,jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Digital Frameworks
tagline:          'Summer quarter 2016'
description:      'Lorem ipsm'
url:              http://digitalframeworks.github.io
baseurl:          /

author:
  name:           'David Eads'
  url:            https://twitter.com/eads

paginate:         10

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/digitalframeworks/digitalframeworks.github.io
